sudo: required
language: generic
services:
    -docker

before_install:
    - docker build -t mokhtar93/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mokhtar93/docker-react npm run test -- --coverage
